name: Bootstrap AWS Resources (State and Lock S3 Buckets)

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  create-resources:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC role assumption
      contents: read   # Required for checking out the code
    environment:
        name: dev  # This can be dynamically set based on your environment
    env:
      AWS_ROLE_ARN: ${{ secrets.AWS_DEV_ROLE_ARN }}  # The role ARN for assuming the dev role
      AWS_REGION: ${{ secrets.AWS_REGION }}  # The AWS region from secrets
      STATE_BUCKET_NAME: ${{ secrets.STATE_BUCKET_NAME }}  # The S3 bucket for state

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS OIDC credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.STATE_BUCKET_NAME }}" \
            -backend-config="key=terraform/state.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="encrypt=true" \
            -backend-config="versioning=true"  # Enable versioning for locking in S3

      - name: Terraform Plan
        run: |
          terraform plan

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
