name: Bootstrap AWS Resources (State and Lock S3 Buckets)

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  create-resources:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC role assumption
      contents: read   # Required for checking out the code
    
    environment:
        name: dev  # This can be dynamically set based on your environment


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS OIDC credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_DEV_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init 

      - name: Terraform Plan
        run: |
          terraform plan

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
