name: Create S3 Buckets for State Files
 
on:
  workflow_dispatch:  # Allows manual triggering
 
jobs:
  create-backend-buckets:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC role assumption
      contents: read   # Required for checking out the code
 
    strategy:
      matrix:
        environment: [dev, staging, prod]
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_DEV_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
 
      - name: Initialize Terraform for S3 bucket
        working-directory: ./backend_setup
        run: terraform init
 
      - name: Plan S3 bucket creation
        working-directory: ./backend_setup
        run: terraform plan -var="environment=${{ matrix.environment }}" -var="region=${{ secrets.AWS_REGION }}" -out="${{ matrix.environment }}-backend.tfplan"
 
      - name: Apply S3 bucket creation
        if: github.event_name == 'workflow_dispatch'
        working-directory: ./backend_setup
        run: terraform apply "${{ matrix.environment }}-backend.tfplan"