name: Deploy to DEV environment

on:
  push:
    branches:
      - 'feature/*'

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC
      contents: read  

    environment:
      name: dev

    env:
      AWS_ROLE_ARN: ${{ secrets.AWS_DEV_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_TF_STATE_BUCKET: ${{ secrets.DEV_TF_STATE_BUCKET }}
      STATE_FILE: dev.tfstate
      LOCK_TAG_KEY: lock
      LOCK_TAG_VALUE: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_DEV_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check and Acquire Lock
        id: acquire_lock
        run: |
          # Check if the lock exists
          LOCK_EXISTS=$(aws s3api get-object-tagging \
            --bucket ${{ secrets.DEV_TF_STATE_BUCKET }} \
            --key ${{ env.STATE_FILE }} \
            --region ${{ secrets.AWS_REGION }} \
            --query "TagSet[?Key=='${{ env.LOCK_TAG_KEY }}'].Value" \
            --output text)

          if [[ "$LOCK_EXISTS" == "${{ env.LOCK_TAG_VALUE }}" ]]; then
            echo "State file is locked. Another operation is currently in progress."
            exit 1
          fi

          # Lock the state file by adding the lock tag
          aws s3api put-object-tagging \
            --bucket ${{ secrets.DEV_TF_STATE_BUCKET }} \
            --key ${{ env.STATE_FILE }} \
            --tagging "TagSet=[{Key=${{ env.LOCK_TAG_KEY }},Value=${{ env.LOCK_TAG_VALUE }} }]" \
            --region ${{ secrets.AWS_REGION }}

          echo "Lock acquired on state file."

      - name: Terraform Init
        run: |
          terraform init \
            -var-file=./environments/dev.tfvars \
            -backend-config="bucket=${{ secrets.DEV_TF_STATE_BUCKET }}" \
            -backend-config="key=${{ env.STATE_FILE }}" \
            -backend-config="region=${{ secrets.AWS_REGION }}"

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=tfplan -var-file=./environments/dev.tfvars

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve tfplan

      - name: Release Lock
        run: |
          # Remove the lock tag
          aws s3api delete-object-tagging \
            --bucket ${{ secrets.DEV_TF_STATE_BUCKET }} \
            --key ${{ env.STATE_FILE }} \
            --region ${{ secrets.AWS_REGION }}
          
          echo "Lock released."
